notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#mapit"
    use_notice: true
    skip_join: true

language: python
env:
  - MODULES="Django==1.2.7 psycopg2==2.4.1"
  - MODULES="Django==1.3.7 psycopg2==2.4.1"
  - MODULES="Django==1.4.5"
  - MODULES="Django==1.5.1"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgdal1-dev libgdal1-1.7.0 python-gdal
  - sudo apt-get install -qq postgresql-9.1-postgis libproj-dev gdal-bin binutils
  - ln -s /usr/lib/python2.7/dist-packages/osgeo ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - ln -s /usr/lib/python2.7/dist-packages/GDAL-1.7.3.egg-info ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - pip install $MODULES --use-mirrors
  - pip install -r project/requirements.txt --use-mirrors
  - wget https://docs.djangoproject.com/en/1.5/_downloads/create_template_postgis-debian.sh
  - sudo -u postgres sh create_template_postgis-debian.sh >/dev/null
  - sudo sh -c 'echo "standard_conforming_strings = off" >> /etc/postgresql/9.1/main/postgresql.conf'
  - sudo /etc/init.d/postgresql reload
  - "echo -e 'MAPIT_DB_NAME: template_postgis\nMAPIT_DB_USER: postgres\nDJANGO_SECRET_KEY: secret' > conf/general.yml"
script:
  - python -Wall project/manage.py test mapit
