notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#mapit"
    use_notice: true
    skip_join: true

language: python

sudo: false

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.8
    - TOXENV=py27-1.9
    - TOXENV=py32-1.8
    - TOXENV=py34-1.9

matrix:
  allow_failures:
    - env: TOXENV=py27-1.9
    - env: TOXENV=py34-1.9

install:
  - pip install tox
before_script:
  - 'if [ $TOXENV != "flake8" ]; then .travis/before_script; fi'
script:
  - tox
